#' CTG Summary Table All Treatments
#'
#' @param ctg_list A list object generated by the dr4pl_fit_loop function
#' @param show A character string specifying what kind of sub titles to
#' display on the plat. Values include "ic50" for the
#' relative IC50, "dss3" for the drug sensitivity score, or "both" for
#' displaying the relative IC50 and the DSS3 score. Defaults to "both".
#' @param font_name A character string specifying the name of the font to use
#' when rendering the table. Defaults to "Albany AMT".
#' See \code{\link[flextable]{font}}.
#' @param font_size_header A numeric value specifying the size of the font
#' for the header of the table. Defaults to 14.
#' See \code{\link[flextable]{fontsize}}.
#' @param font_size_body A numeric value specifying the size of the font
#' for the body of the table. Defaults to 12.
#' See \code{\link[flextable]{fontsize}}.
#' @param use_knit_print A logical value to specify whether the flextable
#' should be printed using \code{\link[knitr]{knit_print}} function
#' instead of the flextable object being returned. Defaults to FALSE.
#'
#' @returns A flextable object
#' @importFrom dplyr mutate select
#' @importFrom flextable align autofit bold hline_top flextable
#' fontsize fp_border_default
#' @importFrom knitr knit_print
#' @importFrom magrittr %>%
#' @importFrom rlang :=
#' @export
#'
ctg_summary_table_all <- function(ctg_list,
                                  show = "both",
                                  font_name = "Calibri",
                                  font_size_header = 14,
                                  font_size_body = 12,
                                  use_knit_print = FALSE) {
  # Extract model data
  data_model <- ctg_list[["model_parameters"]]

  # Calculate max decimal of concentration variable
  max_dec_conc <- as.numeric(max_decimals(ctg_list$monotherapy$concentration))

  # Extract concentrations units
  conc_unit <- as.character(data_model$conc_unit[1])

  # Round variables
  data_model <- data_model %>%
    dplyr::mutate(
      rel_ic50_est = round(rel_ic50_est, max_dec_conc),
      dss3 = round(dss3, 2),
      dose_range = paste0(min_conc, "-", max_conc)
    )

  if(show == "both"){
    # Select and rename variables
    data_model <- data_model %>%
      # Select and rename variables
      dplyr::select(
        "Treatment" = treatment_name,
        "Total\nReplicates" = num_obs,
        "Number of\nDoses" = num_unique_conc,
        !!paste0("Dose\nRange (", conc_unit, ")") := dose_range,
        "Relative\nIC50" = rel_ic50_est,
        "DSS3" = dss3
      )
  }else if(show == "ic50"){
    # Select and rename variables
    data_model <- data_model %>%
      # Select and rename variables
      dplyr::select(
        "Treatment" = treatment_name,
        "Total\nReplicates" = num_obs,
        "Number of\nDoses" = num_unique_conc,
        !!paste0("Dose\nRange (", conc_unit, ")") := dose_range,
        "Relative\nIC50" = rel_ic50_est,
      )
  }else if(show == "dss3"){
    # Select and rename variables
    data_model <- data_model %>%
      # Select and rename variables
      dplyr::select(
        "Treatment" = treatment_name,
        "Total\nReplicates" = num_obs,
        "Number of\nDoses" = num_unique_conc,
        !!paste0("Dose\nRange (", conc_unit, ")") := dose_range,
        "DSS3" = dss3
      )
  }

  # Create flextable object
  flx_tbl <- flextable::flextable(data_model) %>%
    flextable::hline_top(
      border = flextable::fp_border_default(width = 0),
      part = "header"
    ) %>%
    flextable::align(align = "center", part = "header") %>%
    flextable::align(
      align = "center", part = "body",
      j = c(2:ncol(data_model))
    ) %>%
    flextable::align(align = "left", part = "body", j = 1) %>%
    flextable::fontsize(size = font_size_header, part = "header") %>%
    flextable::fontsize(size = font_size_body, part = "body") %>%
    flextable::font(fontname = font_name, part = "body") %>%
    flextable::font(fontname = font_name, part = "header") %>%
    flextable::bold(part = "header", bold = TRUE) %>%
    flextable::autofit()

  # If use_knitr is TRUE, knit the flx_tbl using knit_print,
  # otherwise return the flx_tbl object
  if (use_knit_print == TRUE) {
    knitr::knit_print(flx_tbl)
  } else {
    return(flx_tbl)
  }

  # Return flextable
  return(flx_tbl)
}
