#' Join multiple prepared datasets together
#'
#' @param labguru_plate_data_frame A data frame of a prepared labguru plate map
#' generated by the \code{\link{labguru_plate_prep}} function
#' @param tecan_plate_data_frame A data frame of a prepared Tecan report
#' generated by the \code{\link{labguru_plate_prep}} function
#' @param growth_data_frame A data frame of a prepared Growth file from
#' Incucyte/Cytation generated by the \code{\link{growth_data_prep}} function
#' @param ctg_data_frame A data frame of a prepared CTG file from
#' generated by the \code{\link{ctg_prep}} function
#'
#' @returns A data frame of the respectively joined data files
#' @importFrom magrittr %>%
#' @importFrom dplyr arrange case_when left_join mutate relocate select
#' @importFrom tidyr replace_na
#' @export
#'
#' @examples
#' plate_data_join(labguru_plate_data_frame = NULL,
#' tecan_plate_data_frame = NULL,
#' growth_data_frame = NULL,
#' ctg_data_frame = NULL)
plate_data_join <- function(
    labguru_plate_data_frame = NULL,
    tecan_plate_data_frame = NULL,
    growth_data_frame = NULL,
    ctg_data_frame = NULL){

  # When labguru_plate_data_frame, tecan_plate_data_frame, and
  # growth_data_frame are present
  if(!is.null(labguru_plate_data_frame) &
     !is.null(tecan_plate_data_frame) &
     !is.null(growth_data_frame) &
     is.null(ctg_data_frame)){
    # Join data
    joined_data <- labguru_plate_data_frame %>%
      dplyr::select(-row, -column) %>%
      dplyr::left_join(tecan_plate_data_frame
                       %>% dplyr::select(-row, -column)) %>%
      dplyr::left_join(growth_data_frame)

    # Add media controls
    joined_data <- joined_data %>%
      dplyr::mutate(
        treatment_name = tidyr::replace_na(treatment_name, "Media Only"),
        treatment_type = dplyr::case_when(
          treatment_name == "Media Only" ~ "Media Control",
          TRUE ~ treatment_type)
      ) %>%
      dplyr::arrange(treatment_name, concentration, time)
  }

  # When labguru_plate_data_frame, tecan_plate_data_frame, and
  # ctg_data_frame are present
  if(!is.null(labguru_plate_data_frame) &
     !is.null(tecan_plate_data_frame) &
     is.null(growth_data_frame) &
     !is.null(ctg_data_frame)){
    # Join data
    joined_data <- labguru_plate_data_frame %>%
      dplyr::select(-row, -column) %>%
      dplyr::left_join(tecan_plate_data_frame
                       %>% dplyr::select(-row, -column)) %>%
      dplyr::left_join(ctg_data_frame)

    # Add media controls
    joined_data <- joined_data %>%
      dplyr::mutate(
        treatment_name = tidyr::replace_na(treatment_name, "Media Only"),
        treatment_type = dplyr::case_when(
          treatment_name == "Media Only" ~ "Media Control",
          TRUE ~ treatment_type)
      ) %>%
      dplyr::arrange(treatment_name, concentration)
  }

  # When labguru_plate_data_frame and growth_data_frame are present
  if(!is.null(labguru_plate_data_frame) &
     is.null(tecan_plate_data_frame) &
     !is.null(growth_data_frame) &
     is.null(ctg_data_frame)){
    # Join data
    joined_data <- labguru_plate_data_frame %>%
      dplyr::select(-row, -column) %>%
      dplyr::left_join(growth_data_frame)

    # Add media controls
    joined_data <- joined_data %>%
      dplyr::mutate(
        treatment_name = "Media Only",
        treatment_type = "Media Control") %>%
      dplyr::relocate(c("treatment_name", "treatment_type"),
                      .after = "well") %>%
      dplyr::arrange(well_annotation, time)
  }

  # When labguru_plate_data_frame and ctg_data_frame are present
  if(!is.null(labguru_plate_data_frame) &
     is.null(tecan_plate_data_frame) &
     is.null(growth_data_frame) &
     !is.null(ctg_data_frame)){
    # Join data
    joined_data <- labguru_plate_data_frame %>%
      dplyr::select(-row, -column) %>%
      dplyr::left_join(ctg_data_frame)

    # Add media controls
    joined_data <- joined_data %>%
      dplyr::mutate(
        treatment_name = "Media Only",
        treatment_type = "Media Control") %>%
      dplyr::relocate(c("treatment_name", "treatment_type"),
                      .after = "well") %>%
      dplyr::arrange(well_annotation)
  }

  # When tecan_plate_data_frame and growth_data_frame are present
  if(is.null(labguru_plate_data_frame) &
     !is.null(tecan_plate_data_frame) &
     !is.null(growth_data_frame) &
     is.null(ctg_data_frame)){
    # Join data
    joined_data <- tecan_plate_data_frame %>%
      dplyr::select(-row, -column) %>%
      dplyr::left_join(growth_data_frame)

    # Add media controls
    joined_data <- joined_data %>%
      dplyr::mutate(
        treatment_name = tidyr::replace_na(treatment_name, "Media Only"),
        treatment_type = dplyr::case_when(
          treatment_name == "Media Only" ~ "Media Control",
          TRUE ~ treatment_type)
      ) %>%
      dplyr::arrange(treatment_name, concentration, time)
  }

  # When tecan_plate_data_frame and ctg_data_frame are present
  if(is.null(labguru_plate_data_frame) &
     !is.null(tecan_plate_data_frame) &
     !is.null(growth_data_frame) &
     is.null(ctg_data_frame)){
    # Join data
    joined_data <- tecan_plate_data_frame %>%
      dplyr::select(-row, -column) %>%
      dplyr::left_join(ctg_data_frame)

    # Add media controls
    joined_data <- joined_data %>%
      dplyr::mutate(
        treatment_name = tidyr::replace_na(treatment_name, "Media Only"),
        treatment_type = dplyr::case_when(
          treatment_name == "Media Only" ~ "Media Control",
          TRUE ~ treatment_type)
      ) %>%
      dplyr::arrange(treatment_name, concentration)
  }

  # Return joined data
  return(joined_data)

}
